[mypy]
python_version = 3.12
strict = True

[mypy-tests.*]
disallow_untyped_defs = False
check_untyped_defs = False

[mypy-aiohttp.*]
ignore_missing_imports = True

[mypy-setuptools.*]
ignore_missing_imports = True
